const names = [
    {"threat_name": "Ransomware"},
    {"threat_name": "SQL Injection"},
    {"threat_name": "Social Engineering"},
    {"threat_name": "Phishing"},
    {"threat_name": "Malware"},
    {"threat_name": "Brute Force Attack"},
    {"threat_name": "Cross-Site Scripting (XSS)"},
    {"threat_name": "Denial of Service (DoS)"},
    {"threat_name": "Data Breach"},
    {"threat_name": "Man-in-the-Middle (MitM) Attack"},
    {"threat_name": "Zero-Day Exploit"},
    {"threat_name": "Insider Threat"},
    {"threat_name": "Credential Stuffing"},
    {"threat_name": "Cross-Site Request Forgery (CSRF)"},
    {"threat_name": "Botnet"},
    {"threat_name": "Drive-By Download"},
    {"threat_name": "Session Hijacking"},
    {"threat_name": "Adware"},
    {"threat_name": "Spyware"},
    {"threat_name": "Keystroke Logging"},
    {"threat_name": "Fileless Malware"},
    {"threat_name": "Rootkit"},
    {"threat_name": "Logic Bomb"},
    {"threat_name": "IoT-based Attacks"},
    {"threat_name": "DNS Spoofing"},
    {"threat_name": "Typosquatting"},
    {"threat_name": "Formjacking"},
    {"threat_name": "Watering Hole Attack"},
    {"threat_name": "Cryptojacking"},
    {"threat_name": "Eavesdropping"},
    {"threat_name": "Keylogger"},
    {"threat_name": "Backdoor"},
    {"threat_name": "Trojan Horse"},
    {"threat_name": "Worm"},
    {"threat_name": "Virus"},
    {"threat_name": "Pharming"},
    {"threat_name": "Bot"},
    {"threat_name": "Exploit Kits"},
    {"threat_name": "Distributed Denial of Service (DDoS)"},
    {"threat_name": "SIM Card Swap"},
    {"threat_name": "AI-based Threats"},
    {"threat_name": "Biometric Spoofing"},
    {"threat_name": "E-skimming"},
    {"threat_name": "Zero-Click Exploit"},
    {"threat_name": "Form Grabbing"},
    {"threat_name": "Crypto Malware"},
    {"threat_name": "Clickjacking"},
    {"threat_name": "Macro Virus"},
    {"threat_name": "Ad Fraud"},
    {"threat_name": "Gray Hat Hacking"},
    {"threat_name": "Bluejacking"},
    {"threat_name": "Red Team Attacks"},
    {"threat_name": "Cross-Platform Threats"},
    {"threat_name": "Phreaking"},
    {"threat_name": "Steganography"},
    {"threat_name": "Smishing"},
    {"threat_name": "Vishing"},
    {"threat_name": "Shimming"},
    {"threat_name": "Bait and Switch"},
    {"threat_name": "Session Fixation"},
    {"threat_name": "Ping of Death"},
    {"threat_name": "Hoax"},
    {"threat_name": "Spam"},
    {"threat_name": "Spoofing"},
    {"threat_name": "Impersonation"},
    {"threat_name": "Deep Packet Inspection"},
    {"threat_name": "Malvertising"},
    {"threat_name": "Honeypot"},
    {"threat_name": "Typosquatting"},
    {"threat_name": "Blue Snarfing"},
    {"threat_name": "Blue Bugging"},
    {"threat_name": "AI-powered Cyberattacks"},
    {"threat_name": "File Upload Vulnerability"},
    {"threat_name": "Form-based Attacks"},
    {"threat_name": "Click Fraud"}
];
const threat_names = names.map((name) => name.threat_name);

// ayni olanlari cikar
const uniq = [...new Set(threat_names)];

export default uniq;